services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local,docker
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./ai-models/training:/app/models
    depends_on:
      withoutbg:
        condition: service_started
    networks:
      - ofni-net

  withoutbg:
    image: danielgatis/rembg:latest
    ports:
      - "5000:5000"
    command: ["s", "--host", "0.0.0.0", "--port", "5000"]
    networks:
      - ofni-net

networks:
  ofni-net:
    driver: bridge
