spring:
  application:
    name: ofni-maker

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

app:
  onnx:
    model-path: ../ai-models/training/mobilenetv4_clothing.onnx
  ollama:
    base-url: http://localhost:11434
    model: qwen2.5-vl:7b
  uploads:
    directory: ./uploads
